language: python
python:
  - 2.7
virtualenv:
  # This allows installing python-vtk using apt-get and being able to import it.
  system_site_packages: true
before_install:
  - source .travis_before_install
install:
  # nose is already installed
  - pip install Sphinx
  - pip install coverage
  - pip install coveralls
  # Test against the current master of traits, traitsui and apptools
  - pip install git+http://github.com/enthought/traits.git#egg=traits
  - pip install git+http://github.com/enthought/traitsui.git#egg=traitsui
  - pip install git+http://github.com/enthought/apptools.git#egg=apptools
  - pip install git+http://github.com/enthought/pyface.git#egg=pyface
  - pip install git+http://github.com/enthought/envisage.git#egg=envisage
  - python setup.py develop
script:
  # Running all tests in tvtk/tests and mayavi.
  - coverage erase
  - coverage run -p -m nose.core -v tvtk/tests
  - coverage run -p -m nose.core -v mayavi
  # Run the integration tests.
  - cd integrationtests/mayavi
  - coverage run --rcfile=../../.coveragerc -p run.py
  - cd ../../
  - cp integrationtests/mayavi/.coverage.* ./
  - coverage combine
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
