.TH TVTK_DOC
.SH NAME
tvtk_doc \- A GUI based TVTK documentation search browser.
.SH DESCRIPTION
This manual page documents briefly the
.B tvtk_doc
command.
.PP
.B tvtk_doc 
provides a list of all the available TVTK classes along with
the option to search for the documentation.

The nice thing about the UI is that it performs some kind of
completion on names typed by the user, plus it allows users to search
through the TVTK class docs very easily.  Once a search string is
typed the completion and available lists are modified so you can do
completion of the searched class names.  If a unique enough string is
typed the class docs are shown.
.SH "SEE ALSO"
mayavi2(1), vtk(1)

.SH AUTHORS
Prabhu Ramachandran and others.

This manual page was written by Varun Hiremath <varun@debian.org> for
the Debian GNU/Linux system (but may be used by others).
